apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-bookeezy
spec:
  selector:
    matchLabels:
      app: postgres-bookeezy
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-bookeezy
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: 'IfNotPresent'
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-bookeezy-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres-bookeezy
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/data'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-bookeezy-pv-claim
  labels:
    app: postgres-bookeezy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-bookeezy
data:
  POSTGRES_DB: bookeezydb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-bookeezy
  labels:
    app: postgres-bookeezy
spec:
  ports:
    - name: postgres-bookeezy
      port: 5432
      nodePort: 30432
  type: NodePort
  selector:
    app: postgres-bookeezy
